project:
  type: website
  output-dir: docs

website:
  title: "Shubham Gupta"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/goodhamgupta
      - icon: twitter
        href: https://twitter.com/shubhamg2208
      - icon: linkedin
        href: https://linkedin.com/in/shubhamgupta2208
format:
  html:
    theme: cosmo
    css: styles.css



