project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  site-url: "https://shubhamg.in"
  open-graph: true
  twitter-card:
    creator: "@shubhamg2208"
  title: "Shubham Gupta"
  google-analytics: "G-CLKTGRWBQT"
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/goodhamgupta
      - icon: rss
        href: index.xml
  comments:
    giscus:
      repo: goodhamgupta/personal_blog
  search:
    location: navbar
    type: overlay
  repo-url: https://github.com/goodhamgupta/personal_blog
  repo-actions: [issue]
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
