project:
  type: website
  output-dir: docs

website:
  title: "Shubham Gupta"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/goodhamgupta
  comments:
    giscus:
      repo: goodhamgupta/personal-blog
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css



